changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: New features
      labels:
        - enhancement
        - feature
    - title: Fixes
      labels:
        - bug
        - fix
    - title: Maintenance
      labels:
        - dependencies
        - documentation
        - "*"
